# Dictionary for mapping raw variable names to simplified ones
mapping_dict = {
    "(Z 54) Half of head emerged (DAE)": ["Half of head emerged (DAE)", "Well-Watered season 2023"],
    "(Z 87) Physiological maturity (DAE)": ["Physiological maturity (DAE)", "Well-Watered season 2023"],
    "Aboveground oven-dry biomass - 40 days after emergence (g/m2)": ["Aboveground biomass at 40 DAE (g/m2)", "Well-Watered season 2023"],
    "Aboveground oven-dry biomass - Early grain fill (g/m2)": ["Aboveground biomass at early grain fill (g/m2)", "Well-Watered season 2023"],
    "Aboveground oven-dry biomass - Physiological maturity (g/m2)": ["Aboveground biomass at physiological maturity (g/m2)", "Well-Watered season 2023"],
    "Grain nitrogen content (NIR) (%)": ["Grain nitrogen content (%)", "Well-Watered season 2023"],
    "Grains m2 (Number of grains/m2)": ["Grains per m2", "Well-Watered season 2023"],
    "Grains per spike (Number of grains per spike)": ["Grains per spike", "Well-Watered season 2023"],
    "Harvest index": ["Harvest index", "Well-Watered season 2023"],
    "Maximum Leaf SPAD-502 readings (SPAD)": ["Maximum Leaf SPAD-502 readings (SPAD)", "Well-Watered season 2023"],
    "Maximum NDVI (GreenSeeker) (ndvi)": ["Maximum NDVI", "Well-Watered season 2023"],
    "Oven-dry grain weight per spike (g)": ["Grain weight per spike (g)", "Well-Watered season 2023"],
    "Oven-dry grain yield (g/m2)": ["Grain yield (g/m2)", "Well-Watered season 2023"],
    "Spikes m2 (Number of spikes/m2)": ["Spikes per m2", "Well-Watered season 2023"],
    "Thousand oven-dry grain weight (g)": ["Thousand-grain weight (g)", "Well-Watered season 2023"],
    "(Z 54) Half of head emerged (DAE) [WW_22]": ["Half of head emerged (DAE)", "Well-Watered season 2022"],
    "(Z 54) Half of head emerged (DAE) [WW_23]": ["Half of head emerged (DAE)", "Well-Watered season 2023"],
    "(Z 87) Physiological maturity (DAE) [WW_23]": ["Physiological maturity (DAE)", "Well-Watered season 2023"],
    "Aboveground oven-dry biomass - 40 days after emergence (g/m2) [WW_22]": ["Aboveground biomass at 40 DAE (g/m2)", "Well-Watered season 2022"],
    "Aboveground oven-dry biomass - 40 days after emergence (g/m2) [WW_23]": ["Aboveground biomass at 40 DAE (g/m2)", "Well-Watered season 2023"],
    "Aboveground oven-dry biomass - Early grain fill (g/m2) [WW_22]": ["Aboveground biomass at early grain fill (g/m2)", "Well-Watered season 2022"],
    "Aboveground oven-dry biomass - Early grain fill (g/m2) [WW_23]": ["Aboveground biomass at early grain fill (g/m2)", "Well-Watered season 2023"],
    "Aboveground oven-dry biomass - Physiological maturity (g/m2) [WW_23]": ["Aboveground biomass at physiological maturity (g/m2)", "Well-Watered season 2023"],
    "Grain nitrogen content (NIR) (%) [WW_23]": ["Grain nitrogen content (%)", "Well-Watered season 2023"],
    "Grains m2 (Number of grains/m2) [WW_23]": ["Grains per m2", "Well-Watered season 2023"],
    "Grains per spike (Number of grains per spike) [WW_23]": ["Grains per spike", "Well-Watered season 2023"],
    "Harvest index [WW_23]": ["Harvest index", "Well-Watered season 2023"],
    "Maximum Leaf SPAD-502 readings (SPAD) [WW_23]": ["Maximum Leaf SPAD-502 readings (SPAD)", "Well-Watered season 2023"],
    "Maximum NDVI (GreenSeeker) (ndvi) [WW_23]": ["Maximum NDVI", "Well-Watered season 2023"],
    "Oven-dry grain weight per spike (g) [WW_23]": ["Grain weight per spike (g)", "Well-Watered season 2023"],
    "Oven-dry grain yield (g/m2) [WW_23]": ["Grain yield (g/m2)", "Well-Watered season 2023"],
    "Spikes m2 (Number of spikes/m2) [WW_23]": ["Spikes per m2", "Well-Watered season 2023"],
    "Thousand oven-dry grain weight (g) [WW_23]": ["Thousand-grain weight (g)", "Well-Watered season 2023"]
}